FROM nginx:latest

EXPOSE 80

# run the nginx server in foreground, keeping the container running
CMD ["nginx", "-g", "daemon off;"]


# docker run -d \
# --name kznginx \
# --mount type=bind,source=/Users/kellyhong/Documents/workspace-go/kz/src/kznginx/cert,target=/etc/nginx/ssl/kalay.us/ \
# -p 80:80 \
# -p 443:443 \
# kznginx